stages:
  - build
  - pub

job1:
  stage: build
  script:
    - rm -rf /etc/gitlab-runner/project/air_arctivity_admin
    - mkdir /etc/gitlab-runner/project/air_arctivity_admin
    - cp -r ./* /etc/gitlab-runner/project/air_arctivity_admin
    - echo "build=>cp air_arctivity_admin finish"
  tags:
    - h5
job2:
  stage: pub
  script:
    - kubectl get pod -n web|grep nginx-arctivity-admin | awk '{print $1}'  | xargs kubectl delete pod -n web
    - kubectl get pods --all-namespaces -o go-template='{{range .items}} {{if (or (eq .status.phase "Evicted") (eq .status.phase "Failed" ))}} {{.metadata.name}}{{" "}} {{.metadata.namespace}} {{"\n"}}{{end}} {{end}}' | while read epod namespace; do kubectl -n $namespace delete pod $epod; done;
    - echo "pub=>pod is restart"
  tags:
    -  h5